### ISSUE TITLE
[КСР №2] Установка приложения: Невозможность установить приложение

### ISSUE THREAD

**Issue by AndrewMirugin** [AndrewMirugin/bsu-testing-course#6]
Android App 4

Устройство: Xiaomi Mi5s
ОС: LineageOS 16.0 от 14.04.2019, Android 9.0

![photo5454260814543432445](https://user-images.githubusercontent.com/23194409/58896258-4a6d4100-86fe-11e9-8287-d09cbafed9a4.jpg)

**Comment by vliplianina** [comment]
Это blocker, не critical.
Укажите в описании модель устройства и версию ОС.

Если успеете до зачёта протестировать другую приложения (на выбор) и подготовить отчёт, то у вас будет автомат.
